#!/usr/bin/env bash
#Installing Nginx in my server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
echo "Holberton School" > /var/www/html/index.html
