#!/usr/bin/env bash
#Using a load balanecer

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i '/EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy
sudo echo "listen loadbalancer" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo sed -i '/listen loadbalancer/a \\tbind *:80' /etc/haproxy/haproxy.cfg
sudo sed -i '$ a \\tmode http' /etc/haproxy/haproxy.cfg
sudo sed -i '$ a \\tbalance roundrobin' /etc/haproxy/haproxy.cfg
sudo sed -i '$ a \\tserver 1571-web-01 35.196.114.247 check' /etc/haproxy/haproxy.cfg
sudo sed -i '$ a \\tserver 1571-web-02 34.73.220.28 check' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
