#!/usr/bin/env bash
#loops from 1-10 -badluck for 4th -goodluck for the 8th
n=1
while [ $n -le 10 ]
do 
	if [ "$n" -eq 4 ]
	then
		echo "bad luck"
	elif [ "$n" -eq 8 ]
	then
		echo "good luck"
	else 
		echo "Holberton School"
	fi

	((n++))
done
