#!/usr/bin/env bash
#diplays the time for 12 hours and 59 min
h=0
while [ $h -le 12 ]
do
    echo "Hour: $h"

    min=1

    while [ $min -le 59 ]
    do
        echo $min
        ((min++))
    done

    ((h++))
done