#!/usr/bin/env bash
#script that configures an Ubuntu server
cp /etc/hosts ~/hosts.new
echo "127.0.0.2 localhost" > ~/hosts2.new
echo "8.8.8.8 facebook.com" >> ~/hosts2.new
cp -f ~/hosts2.new /etc/hosts
cat ~/hosts.new >> /etc/hosts
